server:
  port: 8201
spring:
  main:
    web-application-type: reactive
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true #使用小写service-id
      routes: #配置路由路径
        - id: mall-auth
          uri: lb://mall-auth
          predicates:
            - Path=/mall-auth/**
          filters:
            - StripPrefix=1
        - id: mall-admin
          uri: lb://mall-admin
          predicates:
            - Path=/mall-admin/**
          filters:
            - StripPrefix=1
        - id: mall-main
          uri: lb://mall-main
          predicates:
            - Path=/mall-main/**
          filters:
            - StripPrefix=1
        - id: mall-search
          uri: lb://mall-search
          predicates:
            - Path=/mall-search/**
          filters:
            - StripPrefix=1
        - id: mall-demo
          uri: lb://mall-demo
          predicates:
            - Path=/mall-demo/**
          filters:
            - StripPrefix=1
        - id: mall-seckill-acivity
          uri: lb://mall-seckill-acivity
          predicates:
            - Path=/mall-seckill-acivity/**
          filters:
            - StripPrefix=1
        - id: mall-seckill-goods
          uri: lb://mall-seckill-goods
          predicates:
            - Path=/mall-seckill-goods/**
          filters:
            - StripPrefix=1
        - id: mall-seckill-order
          uri: lb://mall-seckill-order
          predicates:
            - Path=/mall-seckill-order/**
          filters:
            - StripPrefix=1
        - id: mall-seckill-reservation
          uri: lb://mall-seckill-reservation
          predicates:
            - Path=/mall-seckill-reservation
          filters:
            - StripPrefix=1
        - id: mall-seckill-stock
          uri: lb://mall-seckill-stock
          predicates:
            - Path=/mall-seckill-stock
          filters:
            - StripPrefix=1
        - id: mall-seckill-user
          uri: lb://mall-seckill-user
          predicates:
            - Path=/mall-seckill-user
          filters:
            - StripPrefix=1

  data:
    redis:
      database: 0
      port: 6379
      host: 10.211.55.3
      password: 12345678

secure:
  ignore:
    urls: #配置白名单路径
      - "/doc.html"
      - "/swagger-resources/**"
      - "/swagger/**"
      - "/*/v2/api-docs"
      - "/*/*.js"
      - "/*/*.css"
      - "/*/*.png"
      - "/*/*.ico"
      - "/webjars/**"
      - "/actuator/**"
      - "/mall-auth/oauth/token"
      - "/mall-auth/rsa/publicKey"
      - "/mall-search/**"
      - "/mall-main/sso/login"
      - "/mall-main/sso/register"
      - "/mall-main/sso/getAuthCode"
      - "/mall-main/home/**"
      - "/mall-main/product/**"
      - "/mall-main/brand/**"
      - "/mall-main/alipay/**"
      - "/mall-admin/admin/login"
      - "/mall-admin/admin/register"
      - "/mall-admin/minio/upload"

sa-token:
  token-name: Authorization
  token-prefix: Bearer
  oauth2:
    is-password: true

management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
