server:
  port: 8090
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://10.211.55.3:3306/sophie_mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true
    username: sophie
    password: 12345678
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*" #不统计这些请求数据
      stat-view-servlet: #访问监控网页的登录用户名和密码
        login-username: druid
        login-password: druid
  data:
    mongodb:
      uri: mongodb://sophie:12345678@10.211.55.3/mall-main?authSource=admin

    redis:
      host: 10.211.55.3
      database: 0
      port: 6379
      password: 12345678
      timeout: 3000ms
      lettuce:
        pool:
          max-active: 200
          max-idle: 10
          max-wait: -1ms

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management: #开启SpringBoot Admin的监控
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

# 自定义redis key
redis:
  database: mall
  key:
    authCode: 'ums:authCode'
    orderId: 'oms:orderId'
    member: 'ums:member'
  expire:
    authCode: 90 # 验证码超期时间
    common: 86400 # 24小时

# 消息队列定义
#rabbitmq:
#  queue:
#    name:
#      cancelOrder: cancelOrderQueue

rocketmq:
  topic: cancelOrderQueue
  access-key: sophie
  secret-key: 12345678
  consumer-group: mall-order-cancel
  tag: '*'
  endpoints: 10.211.55.3:8081


  producer:
    endpoints: 10.211.55.3:8081
    access-key: sophie
    secret-key: 12345678
    topic: cancelOrderQueue

sa-token:
  token-name: Authorization
  oauth2:
    is-password: true


feign:
  okhttp:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
